# permissions for end users to edit tasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: task-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shopkeeper
    app.kubernetes.io/part-of: shopkeeper
    app.kubernetes.io/managed-by: kustomize
  name: task-editor-role
rules:
- apiGroups:
  - interactions.frenchtoasters.io
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - interactions.frenchtoasters.io
  resources:
  - tasks/status
  verbs:
  - get
